all:
	exit 0

	# Clean all
	rm -rf debian/

	# Create base dirs
	mkdir -p debian/minex/usr/share/minex/python/
	mkdir -p debian/minex/usr/share/minex/ui/
	mkdir -p debian/minex/usr/local/share/locale/
	mkdir -p debian/minex/usr/bin/

	# Make the UI
	gtk-builder-convert minex/data/minex.glade debian/minex/usr/share/minex/ui/minex.xml
	cp minex/minex.py debian/minex/usr/share/minex/python/

	# Change paths
	cp minex/minex.py debian/minex/usr/share/minex/python/
	sed -i "s/'..\/bin\/minex.xml'/'\/usr\/share\/minex\/ui\/minex.xml'/g" debian/minex/usr/share/minex/python/minex.py
	sed -i "s/'..\/bin\/minex.png'/'\/usr\/share\/minex\/minex.png'/g" debian/minex/usr/share/minex/python/minex.py
	sed -i "s/POPATH=\"po\"/POPATH=\"\/usr\/local\/share\/locale\"/g" debian/minex/usr/share/minex/python/minex.py

	# Compile it!
	python -mcompileall debian/minex/usr/share/minex/python/

	# Create executable
	echo "#!/bin/bash" > debian/minex/usr/bin/minex
	echo "python minex.pyc" >> debian/minex/usr/bin/minex
	chmod a+x debian/minex/usr/bin/minex

	# Copy image/s
	cp minex/data/minex.png debian/minex/usr/share/minex/

	# Copy i18n
	cp minex/po/es/ debian/minex/usr/local/share/locale/ -R
	cp minex/po/gl/ debian/minex/usr/local/share/locale/ -R

