Document: minex
Title: Debian minex Manual
Author: <insert document author here>
Abstract: This manual describes what minex is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/minex/minex.sgml.gz

Format: postscript
Files: /usr/share/doc/minex/minex.ps.gz

Format: text
Files: /usr/share/doc/minex/minex.text.gz

Format: HTML
Index: /usr/share/doc/minex/html/index.html
Files: /usr/share/doc/minex/html/*.html
